server:
  port: 8080
spring:
  dubbo:
    #dubbo中的服务名称
    application: user-service
    #dubbo的通讯协议
    protocol:
      name: dubbo
    #zookeeper注册中心地址
    registry:
      address: 192.168.221.128:2181
      # zookeeper通讯协议名称
      protocol: zookeeper
    #dubbo的服务扫描路径：因为多个项目都需要用到dubbo并且路径不一样
    base-package: com.my.gamll
logging:
  level:
    root: info
